# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('designation',), 'verbose_name_plural': 'classes'},
        ),
    ]
